/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : La Cisaille
 * Created : 06/20/2016 05:05:24
 */

package controller;

import org.junit.*;
import static org.junit.Assert.*;
import controller.Controller;
import contract.ControllerOrder;
import contract.IView;
import contract.IModel;



public class ControllerTest {

	/**
	 *
	 * @see controller.Controller#control()
	 */
	@Test
	public void control() {
		controller.control();
	}
	
	/**
	 *
	 * @see controller.Controller#orderPerform(ControllerOrder)
	 */
	
	@Test
	public void orderPerform() {
		ControllerOrder controllerOrder = new ControllerOrder();
		controller.orderPerform(controllerOrder);
	}

	/**
	 *
	 * @see controller.Controller#setView(IView)
	 */
	@Test
	public void setView() {
		IView view = new IView();
		controller.setView(view);
	}

	/**
	 *
	 * @see controller.Controller#setModel(IModel)
	 */
	@Test
	public void setModel() {
		IModel model = new IModel();
		controller.setModel(model);
	}

	/**
	 *
	 * @see controller.Controller#spellTest()
	 */
	@Test
	public void spellTest() {
		controller.spellTest();
	}

	

	
}
